/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
      },
      fontFamily: {
        mblack: ["Montserrat-Black", "sans-serif"],
        mblackitalic: ["Montserrat-BlackItalic", "sans-serif"],
        mbold: ["Montserrat-Bold", "sans-serif"],
        mbolditalic: ["Montserrat-BoldItalic", "sans-serif"],
        mextrabold: ["Montserrat-ExtraBold", "sans-serif"],
        mextrabolditalic: ["Montserrat-ExtraBoldItalic", "sans-serif"],
        mextralight: ["Montserrat-ExtraLight", "sans-serif"],
        mextralightitalic: ["Montserrat-ExtraLightItalic", "sans-serif"],
        mitalic: ["Montserrat-Italic", "sans-serif"],
        mlight: ["Montserrat-Light", "sans-serif"],
        mlightitalic: ["Montserrat-LightItalic", "sans-serif"],
        mmedium: ["Montserrat-Medium", "sans-serif"],
        mmediumitalic: ["Montserrat-MediumItalic", "sans-serif"],
        mregular: ["Montserrat-Regular", "sans-serif"],
        msemibold: ["Montserrat-SemiBold", "sans-serif"],
        msemibolditalic: ["Montserrat-SemiBoldItalic", "sans-serif"],
        mthin: ["Montserrat-Thin", "sans-serif"],
        mthinitalic: ["Montserrat-ThinItalic", "sans-serif"],
        malternatesblack: ["MontserratAlternates-Black", "sans-serif"],
        malternatesblackitalic: ["MontserratAlternates-BlackItalic", "sans-serif"],
        malternatesbold: ["MontserratAlternates-Bold", "sans-serif"],
        malternatesbolditalic: ["MontserratAlternates-BoldItalic", "sans-serif"],
        malternatesextrabold: ["MontserratAlternates-ExtraBold", "sans-serif"],
        malternatesextrabolditalic: ["MontserratAlternates-ExtraBoldItalic", "sans-serif"],
        malternatesextralight: ["MontserratAlternates-ExtraLight", "sans-serif"],
        malternatesextralightitalic: ["MontserratAlternates-ExtraLightItalic", "sans-serif"],
        malternatesitalic: ["MontserratAlternates-Italic", "sans-serif"],
        malternateslight: ["MontserratAlternates-Light", "sans-serif"],
        malternateslightitalic: ["MontserratAlternates-LightItalic", "sans-serif"],
        malternatesmedium: ["MontserratAlternates-Medium", "sans-serif"],
        malternatesmediumitalic: ["MontserratAlternates-MediumItalic", "sans-serif"],
        malternatesregular: ["MontserratAlternates-Regular", "sans-serif"],
        malternatessemibold: ["MontserratAlternates-SemiBold", "sans-serif"],
        malternatessemibolditalic: ["MontserratAlternates-SemiBoldItalic", "sans-serif"],
        malternatesthin: ["MontserratAlternates-Thin", "sans-serif"],
        malternatesthinitalic: ["MontserratAlternates-ThinItalic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
